title: Ships
modelClass: JumpLink\Ships\Models\Ship
list: $/jumplink/ships/models/ship/columns.yaml
recordUrl: 'jumplink/ships/ships/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
